source 'https://github.com/CocoaPods/Specs.git'

target 'UnitOfWork', :exclusive => true do
  pod "UnitOfWork", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UnitOfWork", :path => "../"

  pod 'FBSnapshotTestCase'
end
